# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
---
include:
  # Anywhy Flake keyboard no dongle
  - board: xiao_ble//zmk
    shield: anywhy_flake_left
    snippet: studio-rpc-usb-uart
    artifact-name: anywhy_flake_left_standalone
  - board: xiao_ble//zmk
    shield: anywhy_flake_right
    artifact-name: anywhy_flake_right_standalone
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: anywhy_flake_settings_reset_standalone

  # Eyelash Sofle keyboard with the central dongle
  - board: nice_nano//zmk
    shield: eyelash_sofle_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_IDLE_TIMEOUT=300000
    artifact-name: eyelash_sofle_dongle_central_dongle
  - board: nice_nano//zmk
    shield: eyelash_sofle_peripheral_left
    artifact-name: eyelash_sofle_dongle_peripheral_left
  - board: nice_nano//zmk
    shield: eyelash_sofle_peripheral_right
    artifact-name: eyelash_sofle_dongle_peripheral_right
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: eyelash_sofle_dongle_settings_reset

  # Eyelash Sofle keyboard without the central dongle
  - board: nice_nano//zmk
    shield: eyelash_sofle_central_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: eyelash_sofle_standalone_central_left
  - board: nice_nano//zmk
    shield: eyelash_sofle_peripheral_right
    artifact-name: eyelash_sofle_standalone_peripheral_right
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: eyelash_sofle_standalone_settings_reset
